### ISSUE TITLE
Polymer everywhere, really?

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/CurtFramework#1]
We should look into other CSS/HTML5 bootstrapping frameworks to include other options than just polymer, that way everything doesn't end up all fucking googly..

**Comment by davidvthecoder** [comment]
Always a good one:
http://html5boilerplate.com/

Also one I was looking at as far as responsive design is concerned:
http://gumbyframework.com/

**Comment by ninnemana** [comment]
HTML5 Boilerplate is more of syntactically correct HTML. I mean you could include Modernizer and Normalizer, but otherwise, it's all just good practice.

Gumby looks, but it doesn't look like it's very actively developed anymore. Doesn't seem like anyone has touch the repo in 4 months.

I was thinking of something more for just doing responsive grid layouts, but this might just be possible using just polymer.

**Comment by davidvthecoder** [comment]
Dang, I haven't looked at Gumby for a while, didn't see its no longer actively developed.
There was also Foundation:
http://foundation.zurb.com/index.html

though I have not really looked into that one yet.

**Comment by ninnemana** [comment]
Yeah I was thinking about foundation too.

Another possibly very pluggable and lightweight option would be http://bourbon.io. The benefit of bourbon is that you wouldn't have to write your HTML to suit the framework, you can use the framework to suit your HTML just by including mixins in your CSS. Could offer a great amount of flexibility.

**Comment by davidvthecoder** [comment]
Don't lie, you just like the name :beer: 

In all seriousness, Bourbon is good, Since we already are familiar with using SASS, It would be a good supplement.
